-- V1__Initial_Schema.sql
-- Baseline for BadriBhai Apparels Core Schema

-- 1. Categories
CREATE TABLE IF NOT EXISTS categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    slug VARCHAR(255) NOT NULL UNIQUE,
    description TEXT,
    image_url VARCHAR(255),
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 2. Users
CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(255) NOT NULL,
    last_name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    phone_number VARCHAR(255),
    role VARCHAR(20),
    provider VARCHAR(50),
    provider_id VARCHAR(255),
    profile_image VARCHAR(255),
    gender VARCHAR(20),
    date_of_birth VARCHAR(50),
    country VARCHAR(100),
    state VARCHAR(100),
    city VARCHAR(100),
    pincode VARCHAR(20),
    address_line VARCHAR(255),
    is_newsletter_subscribed BOOLEAN DEFAULT FALSE,
    is_active BOOLEAN DEFAULT TRUE,
    two_fa_enabled BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 3. Products
CREATE TABLE IF NOT EXISTS products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    slug VARCHAR(255) NOT NULL UNIQUE,
    description TEXT,
    price DOUBLE PRECISION NOT NULL,
    discount_price DOUBLE PRECISION,
    stock INTEGER NOT NULL,
    category_id BIGINT REFERENCES categories(id),
    brand VARCHAR(255),
    type VARCHAR(255),
    collection VARCHAR(255),
    fabric VARCHAR(255),
    print_type VARCHAR(255),
    occasion VARCHAR(255),
    rating DOUBLE PRECISION DEFAULT 0.0,
    reviews_count INTEGER DEFAULT 0,
    featured BOOLEAN DEFAULT FALSE,
    trending BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Sizes and Colors (ElementCollections)
CREATE TABLE IF NOT EXISTS product_sizes (
    product_id BIGINT NOT NULL REFERENCES products(id),
    sizes VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS product_colors (
    product_id BIGINT NOT NULL REFERENCES products(id),
    colors VARCHAR(255)
);

-- 4. Orders
CREATE TABLE IF NOT EXISTS orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES users(id),
    total_amount DOUBLE PRECISION,
    shipping_address TEXT,
    phone_number VARCHAR(20),
    payment_method VARCHAR(50),
    payment_status VARCHAR(50),
    order_status VARCHAR(50),
    transaction_id VARCHAR(255),
    order_number VARCHAR(255) UNIQUE,
    tracking_number VARCHAR(255),
    courier_name VARCHAR(255),
    shipment_id VARCHAR(255),
    expected_delivery_date TIMESTAMP WITHOUT TIME ZONE,
    shipped_date TIMESTAMP WITHOUT TIME ZONE,
    out_for_delivery_date TIMESTAMP WITHOUT TIME ZONE,
    delivered_date TIMESTAMP WITHOUT TIME ZONE,
    tracking_url VARCHAR(500),
    shipment_status_message TEXT,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 5. Order Items
CREATE TABLE IF NOT EXISTS order_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT REFERENCES orders(id),
    product_id BIGINT REFERENCES products(id),
    variant_id UUID, -- Will be linked properly in V7
    quantity INTEGER NOT NULL,
    price DOUBLE PRECISION NOT NULL,
    selected_size VARCHAR(50),
    selected_color VARCHAR(50)
);

-- 6. Carts
CREATE TABLE IF NOT EXISTS carts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT REFERENCES users(id) UNIQUE,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 7. Cart Items
CREATE TABLE IF NOT EXISTS cart_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cart_id BIGINT REFERENCES carts(id),
    product_id BIGINT REFERENCES products(id),
    variant_id UUID,
    quantity INTEGER NOT NULL,
    selected_size VARCHAR(50),
    selected_color VARCHAR(50)
);

-- 8. Coupons
CREATE TABLE IF NOT EXISTS coupons (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(50) NOT NULL UNIQUE,
    discount_value DOUBLE PRECISION NOT NULL,
    discount_type VARCHAR(20) NOT NULL, -- FIXED, PERCENTAGE
    min_order_amount DOUBLE PRECISION,
    max_discount_amount DOUBLE PRECISION,
    expiry_date TIMESTAMP WITHOUT TIME ZONE,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
